package guardrail

import "strings"

// bashSquote wraps s as a bash single-quoted literal, quotes included.
func bashSquote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// BashDquoteBody escapes s for use inside a bash double-quoted string and
// returns the body only: backslash, backtick, dollar, and double quote.
func BashDquoteBody(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, "`", "\\`")
	s = strings.ReplaceAll(s, "$", `\$`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return s
}

// matchCondition is the shell test matching any of the rule's patterns.
func matchCondition(r Rule) string {
	parts := make([]string, 0, len(r.HookPatterns))
	for _, p := range r.HookPatterns {
		parts = append(parts, `printf '%s' "$command" | grep -qE `+bashSquote(p))
	}
	return strings.Join(parts, " || ")
}

// The generated scripts name the Python generators in their comments; the text
// stays as it is so the Go output is byte-identical to what is deployed.
const blockerHeader = `#!/usr/bin/env bash
# PreToolUse hook that blocks unsafe commands and suggests safe alternatives.
#
# GENERATED by claudewheel.guardrail.generate_blocker_script() from the
# canonical guardrail model. Do NOT edit by hand -- edit guardrail.py and
# regenerate instead.
#
# Reads JSON from stdin (Claude Code's PreToolUse payload). For Bash tool calls
# it matches the command string against the guardrail patterns:
#   - HARD_DENY rules deny for everyone (main agent and subagents).
#   - ESCALATE rules deny ONLY subagents; the main agent falls through silently
#     so the settings ask rule prompts the user.
# The agent_id field is present in the payload only for subagent calls, so a
# non-empty agent_id is how the hook tells a subagent apart from the main agent.

set -uo pipefail

input=$(cat 2>/dev/null || true)
[[ -z "$input" ]] && exit 0

tool_name=$(printf '%s' "$input" | jq -r '.tool_name // empty' 2>/dev/null)
[[ "$tool_name" != "Bash" ]] && exit 0

command=$(printf '%s' "$input" | jq -r '.tool_input.command // empty' 2>/dev/null)
[[ -z "$command" ]] && exit 0

agent_id=$(printf '%s' "$input" | jq -r '.agent_id // empty' 2>/dev/null)

deny() {
    # Build the JSON with jq so the reason string is escaped correctly.
    # Hand-interpolating $1 into JSON breaks when the message contains quotes,
    # producing unparseable output that Claude Code silently discards.
    jq -cn --arg reason "$1" '{hookSpecificOutput: {hookEventName: "PreToolUse", permissionDecision: "deny", permissionDecisionReason: $reason}}'
    exit 0
}
`

// GenerateBlockerScript returns the bash source of hook-block-unsafe-commands:
// the hard-deny rules, then the escalate rules, each in canonical order.
// Hard-deny rules deny everyone (subagent advice when agent_id is set);
// escalate rules deny only subagents.
func GenerateBlockerScript() string {
	lines := []string{blockerHeader}
	for _, r := range RulesByTier(TierHardDeny) {
		lines = append(lines,
			"# "+r.Key+" (HARD_DENY)",
			"if "+matchCondition(r)+"; then",
			`    if [[ -n "$agent_id" ]]; then`,
			`        deny "`+BashDquoteBody(r.SubagentAdvice)+`"`,
			"    else",
			`        deny "`+BashDquoteBody(r.MainAdvice)+`"`,
			"    fi",
			"fi",
			"",
		)
	}
	for _, r := range RulesByTier(TierEscalate) {
		lines = append(lines,
			"# "+r.Key+" (ESCALATE, subagent-only)",
			`if [[ -n "$agent_id" ]] && ( `+matchCondition(r)+" ); then",
			`    deny "`+BashDquoteBody(r.SubagentAdvice)+`"`,
			"fi",
			"",
		)
	}
	lines = append(lines, "exit 0")
	return strings.Join(lines, "\n") + "\n"
}

const adviseHeader = `#!/usr/bin/env bash
# PostToolUse hook that nudges the agent after certain commands run.
#
# GENERATED by claudewheel.guardrail.generate_advise_script() from the
# canonical guardrail model. Do NOT edit by hand -- edit guardrail.py and
# regenerate instead.
#
# Reads JSON from stdin (Claude Code's PostToolUse payload). For Bash tool
# calls whose command matches an ADVISE pattern, it emits additionalContext
# advice. The command has already run; this only nudges. Emits nothing (empty
# stdout, exit 0) when no pattern matches.

set -uo pipefail

input=$(cat 2>/dev/null || true)
[[ -z "$input" ]] && exit 0

tool_name=$(printf '%s' "$input" | jq -r '.tool_name // empty' 2>/dev/null)
[[ "$tool_name" != "Bash" ]] && exit 0

command=$(printf '%s' "$input" | jq -r '.tool_input.command // empty' 2>/dev/null)
[[ -z "$command" ]] && exit 0

advise() {
    # Build the JSON with jq so the advice string is escaped correctly.
    jq -cn --arg ctx "$1" '{hookSpecificOutput: {hookEventName: "PostToolUse", additionalContext: $ctx}}'
    exit 0
}
`

// GenerateAdviseScript returns the bash source of hook-advise-commands: each
// advise rule, in canonical order, emits its advice as additionalContext.
func GenerateAdviseScript() string {
	lines := []string{adviseHeader}
	for _, r := range RulesByTier(TierAdvise) {
		lines = append(lines,
			"# "+r.Key+" (ADVISE)",
			"if "+matchCondition(r)+"; then",
			`    advise "`+BashDquoteBody(r.MainAdvice)+`"`,
			"fi",
			"",
		)
	}
	lines = append(lines, "exit 0")
	return strings.Join(lines, "\n") + "\n"
}
