#!/usr/bin/env bash
#
# Record a driven claudewheel session to an asciicast file.
#
#   scripts/record-demo-cast.sh --dry-run --out demo.cast
#   scripts/record-demo-cast.sh --record --out demo.cast [--cols 128] [--rows 13]
#
# claudewheel is a TUI, so the recording has to be driven: scripts/demo-drive.py
# writes keystrokes on a clock into the recorder, which forwards them to the
# session's pty. What the recording shows is described at the top of that file.
#
# NOTHING REAL IS TOUCHED, and that is the point of the fixture:
#
#   * CLAUDEWHEEL_CONFIG_DIR points at a config directory built inside the work
#     directory. claudewheel generates it from its own defaults and
#     scripts/demo-fixture.py edits invented profiles, accounts, versions,
#     directories and sessions into it, removing every discovery block -- so
#     the session enumerates no real profile, asks gh nothing, fetches no npm
#     listing and never reaches the Anthropic models endpoint.
#   * HOME points inside the work directory too, holding a stub `claude`
#     binary and stub version files. They exist so the client step reports
#     claude as installed and the version segment has binaries to mark; the
#     stub prints one line and exits, so even a launch would start nothing.
#   * The drive never presses RETURN on the segment bar, which is the key that
#     launches. It leaves with `q`, twice.
#
# Everything except the output cast stays in the work directory.

set -euo pipefail

SELF_NAME="$(basename "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

MODE=""
OUT=""
# The recorded terminal. At 128 columns the whole segment bar fits with no
# horizontal scrolling, and 13 rows hold the fan-out above and below the bar
# plus the footer -- and the sessions overview's framed table.
COLS=128
ROWS=13
WORKDIR="$REPO_ROOT/demo-recording.local-only"

usage() {
  cat <<EOF
usage: $SELF_NAME (--dry-run | --record) --out PATH.cast [--cols N] [--rows N] [--workdir DIR]

  --dry-run      print what would be built and recorded, change nothing
  --record       build the fixture and write the asciicast
  --out PATH     where the asciicast goes (required)
  --cols N       recorded terminal columns (default $COLS)
  --rows N       recorded terminal rows (default $ROWS)
  --workdir DIR  fixture directory (default $WORKDIR)
EOF
}

die() {
  echo "$SELF_NAME: $*" >&2
  exit 1
}

while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) MODE="dry" ;;
    --record) MODE="record" ;;
    --out)
      shift
      [ $# -gt 0 ] || die "--out needs a path"
      OUT="$1"
      ;;
    --cols)
      shift
      [ $# -gt 0 ] || die "--cols needs a number"
      COLS="$1"
      ;;
    --rows)
      shift
      [ $# -gt 0 ] || die "--rows needs a number"
      ROWS="$1"
      ;;
    --workdir)
      shift
      [ $# -gt 0 ] || die "--workdir needs a path"
      WORKDIR="$1"
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      usage >&2
      die "unknown argument: $1"
      ;;
  esac
  shift
done

[ -n "$MODE" ] || {
  usage >&2
  die "choose --dry-run or --record"
}
[ -n "$OUT" ] || {
  usage >&2
  die "--out is required"
}
for n in "$COLS" "$ROWS"; do
  case "$n" in
    '' | *[!0-9]*) die "expected a positive integer, got: $n" ;;
  esac
  [ "$n" -gt 0 ] || die "expected a positive integer, got: $n"
done

FIXTURE="$WORKDIR/fixture"
FAKEHOME="$WORKDIR/fakehome"
PROJECT="$FAKEHOME/Projects/myapp"

if [ "$MODE" = "dry" ]; then
  cat <<EOF
$SELF_NAME --record would:

  1. sync $REPO_ROOT/.venv from the lock file
  2. build a fixture workspace:
       $FIXTURE     config directory, generated by claudewheel then patched
                    by scripts/demo-fixture.py (invented options, seeded
                    sessions, every discovery block removed)
       $FAKEHOME    HOME for the session, with a stub claude binary and stub
                    version files under .local/
  3. record a ${COLS}x${ROWS} session of the TUI, driven by
     scripts/demo-drive.py, running in $PROJECT
  4. write the asciicast to $OUT

Nothing outside $WORKDIR and that file is written, and the session makes no
network call.
EOF
  exit 0
fi

for prog in asciinema uv python3; do
  command -v "$prog" >/dev/null 2>&1 || die "required program not found: $prog"
done

mkdir -p "$FAKEHOME/.local/bin" "$FAKEHOME/.local/share/claude/versions" "$PROJECT"
mkdir -p "$FAKEHOME/Projects/site" "$FAKEHOME/work/api" "$FIXTURE"
mkdir -p "$(dirname "$OUT")"

# The stub stands in for the Claude Code binary: the client step reports the
# client as installed when the symlink exists, and the version segment marks
# the files under versions/ as installed.
cat >"$FAKEHOME/.local/bin/claude" <<'STUB'
#!/bin/sh
echo "demo fixture: this is a stub claude binary; nothing was launched"
STUB
chmod +x "$FAKEHOME/.local/bin/claude"
for version in 2.1.14 2.1.9 2.0.32; do
  cp "$FAKEHOME/.local/bin/claude" "$FAKEHOME/.local/share/claude/versions/$version"
done

echo "$SELF_NAME: syncing the virtual environment"
(cd "$REPO_ROOT" && uv sync --frozen --quiet)
VENV_PYTHON="$REPO_ROOT/.venv/bin/python"
[ -x "$VENV_PYTHON" ] || die "no interpreter at $VENV_PYTHON"

echo "$SELF_NAME: generating the fixture config directory"
env HOME="$FAKEHOME" CLAUDEWHEEL_CONFIG_DIR="$FIXTURE" \
  "$VENV_PYTHON" -m claudewheel show >/dev/null
python3 "$SCRIPT_DIR/demo-fixture.py" "$FIXTURE"

# env -i on both sides: the recorded session inherits nothing from the shell
# that started it, so no real token, config directory or PATH entry can reach
# it. The recorder needs its own directory on PATH; the session needs the fake
# home's bin, where the stub claude lives.
ASCIINEMA_DIR="$(dirname "$(command -v asciinema)")"

echo "$SELF_NAME: recording ${COLS}x${ROWS}"
env -i PATH="/usr/bin:/bin" HOME="$FAKEHOME" TERM=xterm-256color \
  python3 "$SCRIPT_DIR/demo-drive.py" \
  | env -i \
    PATH="$FAKEHOME/.local/bin:/usr/bin:/bin:$ASCIINEMA_DIR" \
    HOME="$FAKEHOME" \
    CLAUDEWHEEL_CONFIG_DIR="$FIXTURE" \
    PYTHONPATH="$REPO_ROOT" \
    TERM=xterm-256color \
    COLORTERM=truecolor \
    asciinema rec --overwrite --quiet \
    --cols "$COLS" --rows "$ROWS" \
    --command "sh -c 'cd \"$PROJECT\" && exec \"$VENV_PYTHON\" -m claudewheel --directory \"~/Projects/myapp\"'" \
    "$OUT"

echo "$SELF_NAME: wrote $OUT ($(wc -c <"$OUT") bytes)"
